name: ba_zi_interface
description: interfaces for ba zi algorithms
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  ba_zi_energy:
    git: 
      url: https://github.com/bgoncharuck/ba_zi_energy.git
      ref: e329f6bd335f683c50a5db37782082b097bb4bbd

dev_dependencies:
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
